name: venv
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - pip:
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.0
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - filelock==3.13.1
    - fonttools==4.47.2
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - future==0.18.3
    - gitdb==4.0.11
    - gitpython==3.1.41
    - idna==3.6
    - immutabledict==4.1.0
    - jinja2==3.1.3
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - lightning-utilities==0.10.1
    - llvmlite==0.41.1
    - markupsafe==2.1.4
    - matplotlib==3.8.2
    - mido==1.3.2
    - mir-eval==0.7
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - networkx==3.2.1
    - numpy==1.26.3
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - packaging==23.2
    - pillow==10.2.0
    - platformdirs==4.1.0
    - pretty-midi==0.2.10
    - protobuf==4.25.2
    - psutil==5.9.8
    - pycparser==2.21
    - pyparsing==3.1.1
    - pypianoroll==1.0.4
    - python-dateutil==2.8.2
    - pytorch-lightning==2.1.3
    - pyyaml==6.0.1
    - requests==2.31.0
    - scipy==1.12.0
    - sentry-sdk==1.39.2
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - soxr==0.3.7
    - sympy==1.12
    - threadpoolctl==3.2.0
    - torch==2.1.2
    - torchaudio==2.1.2
    - torchmetrics==1.3.0.post0
    - torchsummary==1.5.1
    - torchvision==0.16.2
    - tqdm==4.66.1
    - triton==2.1.0
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - wandb==0.16.2
    - yarl==1.9.4
